### ISSUE TITLE
[Note] - Highlight lines of code in block

### ISSUE THREAD

**Issue by firasm** [open-resources/dash_curriculum#18]
![Screen Shot 2022-03-18 at 12 59 43 PM](https://user-images.githubusercontent.com/2507459/159075271-4afaa72f-294c-4757-99fe-ad2c61041e46.png)

**Comment by apdcode** [comment]
@firasm Did you find a way to highlight certain lines within a code block?

**Comment by firasm** [comment]
Nope - not as of yet....it's not supported by any official markdown specs, so would have to write some CSS and create something ourselves.

**Comment by Coding-with-Adam** [comment]
@firasm @apdcode , I don't think this is feasible either and maybe not worth our time trying to write our own CSS, unless you want to take another stab at this. Otherwise, I'll close this issue. 

Let me know what you prefer.

**Comment by Coding-with-Adam** [comment]
Keeping this open so Firas can work on it later.

**Comment by firasm** [comment]
Note to self: Look into this https://codehike.org/
