### ISSUE TITLE
Select dataset for Chapter 7 onwards

### ISSUE THREAD

**Issue by firasm** [open-resources/dash_curriculum#19]
Put ideas here!

Something that shows off:

- [ ] multiple dash components
- dash table?
- different plot types

**Comment by joelostblom** [comment]
I think it would be great if we could have a dataset that is both globally relevant and communicates an important message. However, given the time constraints, I don't think we should spend too much time trying to find a novel one. A few suggestions that could communicate something interesting are:

- Gapminder
- The one that was used in this dashboard on life expectancy https://life-expectancy-indicator-app.herokuapp.com/
- The one that was used in this dashboard for energy consumption https://world-energy-consumption-app.herokuapp.com/

It would be cool to use something from Our World In Data, but my experience is that there are often several different datasets that need to be used to tell a story. For example what we are doing in slide deck 1 here about deforestation, cattle, and palm oil https://viz-learn.mds.ubc.ca/en/module6.

There is also the one that was used in this dashboard for movie attributes such as ratings https://movie-selection-app.herokuapp.com/. It has relevance and utility, but nothing that important to communicate.

**Comment by Coding-with-Adam** [comment]
I really liked the data set on deforestation because it is both globally relevant and communicates an important message. And I think this data set will be relevant for many years to come, especially if it can be updated as they years pass by. We can also use multiple Dash components with that data set.

**Comment by firasm** [comment]
Hey @joelostblom feel free to make an executive decision on this, I'm quite swamped this week!

**Comment by firasm** [comment]
Maybe not the movies dataset, I hate that one 😂

**Comment by apdcode** [comment]
Deforestation sounds really interesting! However, like with depleting marine life and dying coral reefs, it can be a bit depressing.
Gapminder, despite all its flaws, is at least a bit positive in some ways with increasing life expectancies in most (all?) countries as an example. On the other hand, that's not too good for the planet either. So, who knows... But with gapminder one could at least easily defend namedropping Hans Rosling, which is never a bad thing. And it's easily accessible through `px.data.gapminder()`

**Comment by Coding-with-Adam** [comment]
Good point @apdcode

**Comment by Coding-with-Adam** [comment]
Data set selected was gapminder from px.data.gapminder()
