### ISSUE TITLE
Should we recommend an IDE? Any setup needed to be added to the intro chapter?

### ISSUE THREAD

**Issue by joelostblom** [open-resources/dash_curriculum#22]

**Comment by Coding-with-Adam** [comment]
We actually recommend installing and using VS Code in chapter 0. @joelostblom would you like us to mention it somewhere else again?

**Comment by joelostblom** [comment]
Nope I just missed that. Are there any VS Code extensions that are really critical for working with Dash? Maybe the Python extension? Then we could just mention those and close this issue.

**Comment by Coding-with-Adam** [comment]
Yes, Python extensions is VS Code is mentioned there. I just double-checked. We can close this issue. 

@joelostblom what's common practice in working together on github? does the person that created the issue close it, or should any of the maintainers (you, Firas, me) feel free to close the issue?

**Comment by joelostblom** [comment]
Great, then let's close this. In general I think different repos does different. Some devs close issues quickly to avoid build up, others comment and gives the issue opener a chance to close which is less efficient but could be seen as more welcoming. For our small project I think is fine if either of us does it.
