### ISSUE TITLE
Start with a simpler layout example in chapter 3

### ISSUE THREAD

**Issue by joelostblom** [open-resources/dash_curriculum#24]

**Comment by Coding-with-Adam** [comment]
@joelostblom you mean keep the layout example that is there, but add a simpler example right above it?

**Comment by joelostblom** [comment]
Yes correct!

**Comment by Coding-with-Adam** [comment]
@apdcode Arne, would you be ok with adding a simpler layout example prior to the one you finish with in chapter 3. Maye a layout with just one row component and two column components:
```
app.layout = dbc.Container([
    dbc.Row([
        dbc.Col([
            whichever-dcc-component
        ], width=6),
        dbc.Col([
            whichever-dcc-component
        ], width=6)
    ])
])
```

**Comment by Coding-with-Adam** [comment]
Added another simpler layout example to [chapter 3.](https://github.com/open-resources/dash_curriculum/blob/main/tutorial/part1/chapter3.md)
