### ISSUE TITLE
Standardize the use of admonitions such as note, tip etc

### ISSUE THREAD

**Issue by joelostblom** [open-resources/dash_curriculum#26]

**Comment by Coding-with-Adam** [comment]
Definitely makes sense. How do you suggest we go about this? Should we discuss this on Friday? Could you or @firasm give us guidance on best practice for note, tip usage?

**Comment by joelostblom** [comment]
I don't think this is a big thing, so I am fine with using either note, info, or tip for the "extra info" type admonition. Tip is nice because it has the light bulb and note/info is nice because they are blue which is a bigger contrast to the yellow in warning admonitions that we also use (we could also make a custom with a light bulb and blue color, but I think that is unnecessary)

**Comment by Coding-with-Adam** [comment]
Ok, I like the tip because of the lightbulb. But maybe it could be a group decision under your guidance. 
How about we wait for you to join us on Friday, at which point you could bring this up, giving the group the options they could choose from. Does that sound ok by you?

**Comment by joelostblom** [comment]
Sounds good!

**Comment by Coding-with-Adam** [comment]
Team agreed to use tips and notes more conscientiously. And Adam made note to review notes, tips, info, warning to ensure there is consistency when doing final review.
