### ISSUE TITLE
Fix relative links in JupyterBook

### ISSUE THREAD

**Issue by firasm** [open-resources/dash_curriculum#32]
I would also prefer relative links but the relative links we are currently using are not working which is why I changed it:

![image](https://user-images.githubusercontent.com/4560057/163818686-86f9c680-f06e-42a9-8b0d-d43d7214da19.png)

I actually always have issues with relative link in JupyterBook, which clearly means I must be doing something wrong. @firasm do you know what the path should look like? Or do we need to manually copy linked files somewhere (seems tedious).

_Originally posted by @joelostblom in https://github.com/open-resources/dash_curriculum/pull/21#discussion_r852135333_

**Comment by firasm** [comment]
I think we just need to fiddle with `html_extra_path:` in `_config.yml`. I'll fix this later!

**Comment by Coding-with-Adam** [comment]
I think the relative links are working now, but definitely double check, @firasm , whenever you have the time.
