### ISSUE TITLE
Prettify navigation menu

### ISSUE THREAD

**Issue by joelostblom** [open-resources/dash_curriculum#46]
I think we should remove "Chapter" and "Part" from the navigation side menu to make it less wordy and aim for something that looks like this (but open for discussion):

![image](https://user-images.githubusercontent.com/4560057/172940533-390de872-f370-4ea4-9e59-fb61cac838e7.png)

We don't need to manually number either but can use `numbered: true` https://github.com/QuantEcon/lecture-python.myst/blob/main/lectures/_toc.yml

**Comment by firasm** [comment]
Ok I agree - Part X is redundant, and we can use the automatic numbering
