### ISSUE TITLE
App in section 10.2 never showing "My first app. The button has not been clicked yet."

### ISSUE THREAD

**Issue by gabri-al** [open-resources/dash_curriculum#63]
The first app in section 10.2 is not showing "My first app. The button has not been clicked yet." but shows
"My first app with a button that I have clicked None times."
I believe this is due because the n_clicks is by default None at first and the app only includes a check on n_clicks == 0.
I think a similar thing is happening with the next app.

Probably all buttons in 10.2 should be instantiated with n_clicks = 0.

**Comment by Coding-with-Adam** [comment]
Good catch, @gabri-al . I just updated the code. It works now.
